version: '3.8'

services:
  backend:
    build: ./be
    ports:
      - "5000:5000"
    volumes:
      - ./be/static/images:/app/static/images
      - keras-cache:/root/.keras
    env_file:
      - ./be/.env
    environment:
      # - DB_HOST=${DB_HOST}
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    depends_on:
      - database


  database:
    image: ankane/pgvector:latest
    env_file:
      - ./be/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  frontend:
    build: ./fe
    ports:
      - "8080:80"
    depends_on:
      - backend


volumes:
  pgdata:
  keras-cache:


