version: '3.8'

services:
  web_be:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/images:/app/static/images
      - keras_cache:/root/.keras
      - .:/app  # Mount thư mục code từ host vào container
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1  # Hiển thị log Python ngay lập tức
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
  keras_cache:
